import api.app as api_module
from api.advanced_risk import install_advanced_risk
from api.backtest import install_backtester
from api.intelligence import install_intelligence
from api.market_data import install_market_data
from api.portfolio_constraints import install_portfolio_constraints
from api.research import install_research
from api.research_execution import install_research_execution_model
from api.risk_gate import install_risk_enforcement, register_risk_gate
from api.decision_engine import register_decision_engine
from api.runtime_hardening import install_runtime_hardening
from api.security import install_security
from api.shadow_mode import install_shadow_mode
from api.system_readiness import install_system_readiness

app = api_module.app

install_security(api_module)
install_intelligence(api_module)
install_portfolio_constraints(api_module)
install_advanced_risk(api_module)
install_runtime_hardening(api_module)
install_risk_enforcement(api_module)
install_market_data(api_module)
install_system_readiness(api_module)
install_backtester(api_module)
install_research_execution_model()
install_research(api_module)
install_shadow_mode(api_module)
register_risk_gate(app)
register_decision_engine(app)
