from enum import Enum


class OrderState(str, Enum):
    NEW = "NEW"
    VALIDATED = "VALIDATED"
    RISK_APPROVED = "RISK_APPROVED"
    QUEUED = "QUEUED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    MONITORING = "MONITORING"
    EXITED = "EXITED"
    ARCHIVED = "ARCHIVED"